### ISSUE TITLE
generator.generateSequence throwing index rangeError

### ISSUE THREAD

**Issue by dhcracchiolo** [patchandthat/wave-generator#4]
In data_chunk8.dart line 44 and 52 the original file rounds down causing the loop index to go out of bounds.  I just changed the two to round up and all is well.

Use my fork: https://github.com/dhcracchiolo/wave-generator

P.S. Thanks for the awesome plugin :)

**Comment by novas1r1** [comment]
Thank you @dhcracchiolo - this really helped me!
